The Cyclone system is loosely inspired by the famous Enigma machine. I picture the Cyclone machine as a stack of spinning discs or wheels (which inspired the name). 

The key is an $n \times n $ square matrix, with each row of integers representing a permutation in the form $[ f(1) \quad f(2) \quad ... f(n-1) \quad f(n) ]$. Especially for $n = 27$, it's nice to use the alphabet and the underscore to represent the key.




In [118]:
using Random
using Printf
const Symbol = Int64
n  = 27
function randomkey(n)
    k =zeros(Symbol, n, n)
    for i in 1:n
        k[i,:] = Random.randperm(n)
    end
    k
end

function printsymbol(s)
    if s <= 26 
        print(Char(s+64)," ") 
    else
        print("_ ")
    end
end

function printvec(v)
    for i in 1:length(v)
        #@printf "%d " i
        printsymbol(v[i])
    end
    @printf "\n"
end

function printkey(k)
    for i in 1:size(k)[begin]
        printvec(k[i,:])
    end
end
        
  
k = randomkey(n)
printkey(k)


J C E K T U L A B H F R V Z X I S G Y D N _ Q W P O M 
P _ F T Z G C A E K W L X U Q S O H V N M I J B R Y D 
G Y _ L C O M T A Z B R P J F W S U H X D N Q V K I E 
Y _ H N X P D R J W V S T L M K I U Z A O C F E Q B G 
T G O W F Y J B D N I V S H Z M Q R A U X C K L E _ P 
O H Y E N W _ X B C R Z D Q F L I V M K G T P U J S A 
N H D L E I A K O T G V Q B Z U J Y F P C _ W X R M S 
X P U M O K _ W G Y C H L F A E N T R Q V S D J Z B I 
A _ H V Y W E K U J B I S G L F T P C Q R X Z N M O D 
S N G K R V Z H C E B A _ U X O M J Y P F D T Q L I W 
Z M U G A Y O P E _ H I S V N D B Q W F R X L C J K T 
M O L F Y A H S J X B T U K Q R G Z I V W N P E _ C D 
L X _ P T E C F W A Y O J N Z G D S I K B R H Q M U V 
H A K G U W R X Z Y V T L S J F M P Q _ I C N B O E D 
P Q C E H T O Z U S K N A I Y W J _ G X L F B D V R M 
A S B J G _ I V M X F Y U K P Q C T R E W H N O D Z L 
A Q K _ D W S V X O T Z I M B F L P U J E R Y C N H G 
T A E H S Z N K G B R _ L M V X J D C Y U Q P F I W O 
C H G F A 

In [60]:
function safe(i,n)
    if i > n
        i = i - n
    end
    if i < 1
        i = i + n
    end
    i
end
;

In [61]:
function randomkey(n)
    k =zeros(Symbol, n, n)
    for i in 1:n
        k[i,:] = Random.randperm(n)
    end
    k
end
        
  
k = randomkey(n)
;

In [62]:
function getf(k,s)
    n = size(k)[begin]
    f = zeros(Symbol,n)
    for i in 1:n
        x = i
        for j in 1:n
            x = k[ j, safe(x+s[j],n)  ]
        end
        f[i] = x
    end
    f
end
    
    

getf (generic function with 1 method)

In [63]:
function encode(p,k)
    l = length(p)
    c = zeros(Symbol,l)
    n = size(k)[begin]
    s = zeros(Symbol,n)
    for i in 1:l
        f = getf(k,s)
        c[i] = f[p[i]]
        for j in 1:n
            s[j] = safe(f[j]+s[j],n)
        end
    end
    c
end

       

encode (generic function with 1 method)

In [64]:
function inverse(f)
    g = zeros(Symbol, length(f))
    for i in 1:n
        g[i] = findfirst(isequal(i),f)
    end
    g
end
    
        
    
    

inverse (generic function with 1 method)

In [65]:
function decode(p,k)
    l = length(p)
    c = zeros(Symbol,l)
    n = size(k)[begin]
    s = zeros(Symbol,n)
    for i in 1:l
        f = getf(k,s)
        g = inverse(f)
        c[i] = g[p[i]]
        for j in 1:n
            s[j] = safe(f[j]+s[j],n)
        end
    end
    c
end


decode (generic function with 1 method)

In [66]:
function printvec(v)
    for i in v
        @printf "%d " i
    end
    @printf "\n"
end

printvec (generic function with 1 method)

In [74]:
function encrypt(p, k, r)
    for i in 1:r
        p = encode(p,k)
        p = reverse(p)
    end
    p
end

function decrypt(p, k, r)
    p
    for i in 1:r
        p = reverse(p)
        p = decode(p,k)
    end
    p
end
    







;


In [70]:
p = Random.randperm(n)
c = encrypt(p,k,r)
d = decrypt(c,k,r)
printvec(p)
printvec(c)
printvec(d)
p == d




LoadError: MethodError: no method matching reverse(::Nothing)

Closest candidates are:
  reverse(::Tuple)
   @ Base tuple.jl:562
  reverse(::Pair{A, B}) where {A, B}
   @ Base pair.jl:53
  reverse(::NamedTuple)
   @ Base namedtuple.jl:324
  ...


In [76]:
for i in 1:10
    p = Random.randperm(n)
    c = encrypt(p,k,i)
    d = decrypt(c,k,i)
    printvec(p)
    printvec(c)
    #printvec(d)
    print(i, p == d)
    @printf "\n"
end
    

2 9 6 3 8 1 7 4 5 
6 5 1 3 1 4 4 1 4 
1true
9 2 8 3 6 4 5 7 1 
8 8 4 9 8 8 3 5 9 
2true
8 9 4 7 6 3 2 1 5 
3 8 8 4 1 2 4 7 7 
3true
8 3 1 5 7 9 2 4 6 
9 7 1 5 3 5 3 3 5 
4true
8 7 6 1 3 2 5 4 9 
8 4 6 7 1 1 5 6 1 
5true
4 3 6 5 8 7 2 1 9 
4 4 8 7 7 2 9 4 9 
6true
2 3 1 5 9 7 8 4 6 
3 6 7 7 9 7 7 8 6 
7true
5 9 3 7 1 2 6 4 8 
5 5 6 7 9 2 1 6 8 
8true
7 8 3 1 9 6 4 2 5 
6 5 6 8 5 8 4 8 8 
9true
4 7 2 3 1 6 8 5 9 
8 2 2 2 5 9 1 6 1 
10true


In [75]:
encrypt(p,k,1)

9-element Vector{Int64}:
 8
 7
 2
 4
 2
 5
 8
 3
 9

In [77]:
k


9×9 Matrix{Int64}:
 4  3  7  8  5  9  6  2  1
 9  1  3  5  2  7  6  8  4
 9  5  2  6  4  1  7  8  3
 5  4  2  8  1  7  9  6  3
 1  5  6  2  8  7  9  3  4
 1  5  6  8  9  3  4  2  7
 6  1  5  8  4  3  9  7  2
 9  2  1  4  6  8  7  3  5
 3  1  7  4  2  9  8  5  6

In [79]:
circshift!(k[1,:],1)


9-element Vector{Int64}:
 1
 4
 3
 7
 8
 5
 9
 6
 2

In [83]:
K = zeros(Symbol, (n,n))
K[1,:] = circshift(k[1,:],1)
K

9×9 Matrix{Int64}:
 1  4  3  7  8  5  9  6  2
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0  0

In [84]:
function spin(k,r)
    n = size(k)[begin]
    s = zeros(Symbol,n)
    for i in 1:r
        f = getf(k,s)
        for j in 1:n
            s[j] = safe(f[j]+s[j],n)
        end
    end
    K = zeros(Symbol,(n,n))
    for j in 1:n
            K[j,:] = circshift(k[j,:],s[j])
    end
    K
end
    

spin (generic function with 1 method)

In [88]:
k = spin(k,10)

9×9 Matrix{Int64}:
 7  8  5  9  6  2  1  4  3
 1  3  5  2  7  6  8  4  9
 7  8  3  9  5  2  6  4  1
 5  4  2  8  1  7  9  6  3
 5  6  2  8  7  9  3  4  1
 2  7  1  5  6  8  9  3  4
 6  1  5  8  4  3  9  7  2
 5  9  2  1  4  6  8  7  3
 7  4  2  9  8  5  6  3  1

In [91]:
function printsymbol(s)
    print(Char(s+64))
end

printsymbol (generic function with 1 method)

In [93]:
printsymbol(k[1,1])

G

In [94]:
function numcode(x)
    Char(x)
end

numcode (generic function with 1 method)

In [95]:
numcode('c')

'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)

In [96]:
codepoint('a')

0x00000061

In [97]:
Symbol(codepoint('a'))

97

In [109]:
function vecfromstring(s)
    n = length(s)
    v = zeros(Symbol,n)
    for i in 1:n
        if occursin(s[i:i],"ABCDEFGHIJKLMNOPQRSTUVWXYZ")
            v[i] = Symbol(codepoint(s[i]) - 64)
        else
            v[i] = Symbol(27)
        end
    end
    v
end
        
        
    

vecfromstring (generic function with 1 method)

In [113]:
vecfromstring("ABC_EFG")

7-element Vector{Int64}:
  1
  2
  3
 27
  5
  6
  7

In [103]:
occursin("a", "abc")


true

In [104]:
s = "test"


"test"

In [107]:
s[begin:begin]

"t"

In [119]:
F = Set()

Set{Any}()

In [120]:
p = Random.randperm(9)

9-element Vector{Int64}:
 3
 8
 4
 2
 6
 1
 7
 5
 9

In [125]:
circshift(p,2)

9-element Vector{Int64}:
 5
 9
 3
 8
 4
 2
 6
 1
 7

In [122]:
push!(F,p)

Set{Any} with 1 element:
  [3, 8, 4, 2, 6, 1, 7, 5, 9]

In [123]:
length(F)

1